= GIT BEST PRACTICES
Doc Writer <santos.r09@gmail.com>
:toc:

GIT SQUASH:
https://www.youtube.com/watch?v=RwvTrSm7zEY

GIT FOR PROFESSIONAL:
https://www.youtube.com/watch?v=Uszj_k0DGsg

GIT MERGE AND REBASE:
https://www.youtube.com/watch?v=7Mh259hfxJg


== THE 'PERFECT' COMMIT
=== Add the _right_ changes
Instead cram everything into one commit, add changes from a single topic.
* Select what should go into the next commit.
** Select specific files or parts of those files for the next commit.

Command:
_git add *-p* example.html_

Flag _*-p*_ for patch level
At patch level we could see every changes and decide if should be included or not

----
git add -p example.html

output example:
(1/2) Stage this hunk [y,n,g,a,d,j,J,g,/,e,?]?

_You should answer Yes or Not: *y* or *n*_
----

* Separate different topics in the commits.



=== Compose a good commit message
*Subject:* Concise summary of what happened

*Body:* More detailed explanation
* What is now different than before?
* What is the reason for the change?
* Is there anything to watch out for / anything particularly remarkable?

Command:
git commit

This will open a window editor, were you should type the commit message, *The first Line will be the Subject of the message, if you add a blank line, git will understand that after the blank Line this will be the Body Message*, put your comments, and save the file.


== BRANCHING STRATEGIES
Create a Written Convention, Agree on a branching workflow for your team.
. Git allows you to create branches, but it dosen't tell you how to use them.
. You need a written best practice of how work is ideally structured in your team, to avoid mistakes & collisions.
. It highly depends on your team / team size, on your project, and how you handle releases.
. It helps to onboard new team members("This is how we work here").

=== Integrating changes and structuring releases
==== Mainline Development, Always be integrating
* Few branches
* Relatively small commits
* High-quality testing & QA standards

==== State, release and feature branches
* Different types of branches
* Fulfill different types of jobs

===== Long-Running and Short-lived branches
*Long-running branches*
* Exist through the complete lifetime of the project.
* Often, they mirror "stages" in your dev life cycle.
* Common convention: no direct commits, merge or rebase integration through PR.

*Short-lived branches*
* For new features, bug fixes, refactorings, experiments
* Will be deleted after integration(merge/rebase)

The Best branching model?
- Consider your project, release cycle, and team
- Take ispiration from existing models
- Create your own model.

== PULL REQUESTS
*Communicating about and Reviewing code*





== GIT MERGE AND REBASE

=== Merging
Steps to merge:
. Switch to or checkout the branch you want to merge the changes into(the reciving branch)
. Use the *git merge* command to merge changes from a specific branch into the current branch.

*Fast-Forward*
The recieving branch simply caught up the commits from the merging branch.

*Not all merges are fast-forwards*
This happens when the master branch has diverged, has recievied commits from another teammate.
In this case, rather than performing a simple fast-forward, git generates a merge commit replaing all the changes made on the Bugfix branch since it diverged from master and record the changes in a new merge commit on Master

*Merges are forward focused*
The existing commits on both branches remain untouched. Git merge does not mess with existing history in any way.

*CONS*
Due to the bunch of commits(merges commits) generated by the merge process the history's commits could get muddy and messy. Rebasing to the rescue.

=== Rebasing
We can rebase the feature branch onto the master branch. This moves the entire feature branch so that *it BEGINS at the tip of the master branch.* All of the work is still there, but *we have re-written history.*

Instead of using a merge commit, rebasing rewrites history by creating new commits for each of the original feature branch commits.

----
git switch feature
git rebase master
----

The master branch is unchanged.
The feature branch commits are all new

Why rebase?
* much cleaner project history.
* No unnecessary merge commits
* we end up with a linear project history
* We can use rebase command to reword commits, drops commits, or even squash a branch down to a single commit as git rebasing.

WARNING: Never rebase commits that have been shared with others. If you have already pushed commits up to Github DO NOT rebase them unless you are positive no one on the team is using those commits OR you feel comfortable breaking this golden rule.
*DO NOT REWRITE ANY GIT HISTORY THAT OTHER PEOPLE ALREADY HAVE. IT'S A PAIN TO RECONCILE THE ALTERNATE HISTORIES. NOTHNING WILL MATCH UP.*

==== Summary
*Merging*
Pros
* Keeps the original history intact
* Fully traceable history
* Less scary for begginers

Cons
* History can become super muddied with a ton of merge commits.

*Rebasing*
Pros
* History is flat & easy to read
* Nice and clean

Cons
* Can be dangerous
* Can lose some context(mainly an issue with squashing)

== GIT SQUASH
Combining multiple commits into one

Squashing can help keep your Git history tidier and easier to read. Squashing retains all the changes you made but condenses them down into a single commit.
Squash and rebase your git commits

=== Interactive Rebase
Running git rebase with the -i option will enter the interactive mode, which allows us to squash commits, reword commit messages, add files, drop commits, and more.
We need to specify how far back we want to rewrite commits. You can also provide a commit hash.

----
git rebase -i HEAD~4
----

*What now?*
In our text editor, we'll see a list of commits alongside a list of commands that we can choose from.
*pick* - use the commit
*reword* - use the commit, but edit the commit message.
*edit* - use commit, but stop amending
*squash* - meld into previous commit
*drop* - remove commit

=== Squashing
To squash commits, replace "pick" with "squash" for each commit that you want to squash.
Then, save the file and close it.
Git will perform the rebase, squashing the commits, and then will prompt you to edit the newly rewritten commit message.


=== Squashing on merge
Alternatively, we can squash all commits from a feature branch together when merging.

The --squash option will take all changes from the feature branch and apply them to the current branch.
Then we need to generate a new commit using git commit.

----
_git reset --hard HEAD@{7}_


git merge --squash feature


----



git log --oneline


