= Spring Cloud
Provides tools for developers to quickly  build some fo the common patterns in distributed systems: eg. configuration management, service delivery, circuit breakers, intelligent routing, micro-proxy, control bus, one-time tokens, global locks, leadership election, distributed sessions, cluster state.


=== Spring Cloud Config Server
Use a Git repository to expose the configuration of each ms

=== Dynamic Scale up and Down
* Naming Server(Eureka)
* Ribbon, Spring Cloud LoadBalancer (Client Side Load Balancing)
* Feign (Easier REST Clients)

Distribute the Load between all the instances of microservices.

Ribbon Load Balancing
Ribbon -> NamingServer

=== VISIBILITY AND MONITORING
* Zipkin Distributed Tracing
* Netflix API Gateway

=== FAULT TOLERANCE
* Hystrix, Resilience4j

== MICROSERVICES COMPONENTS - EXAMPLE PROJECT
PORTS
[cols="1,1"]
|===
|Limits Service 
|===
|8080,8081
|===

Spring Cloud Config Server : 8888
Currency Exchange Service 8000, 8001, 8002
Currency Conversion Service : 8100 8101 8102
Netflix Eureka Naming Server : 8761
Netflix Zuul API Gateway Server : 8765
Zipkin Distributed Tracing Server : 9411


== MS- EXAMPLE PROJECT: LIMITS SERVICE

=== Spring Initializer
Dependencies:
Spring Web
Spring Boot DevTools
Spring Boot Actuator
Config Client


=== Spring config
In the application.properties add this:
spring.config.import=optional:configserver:http://localhost:8888

=== Limits service
add Limits in the properties
limits-service.minimum=2

create the Configuration class to get the values from the properties


== CENTRALIZED CONFIGURATION
=== SPRING CLOUD CONFIG SERVER
Dependencies:
DevTools
Config Server

Configure the server port to run the app, in the application.properties:
server.port=8888

As a good practice give names that describe the propuse
spring.application.name=spring-cloud-config-server

== GIT REPOSITORY

Intall Git client in local machine

create the folder:
git-localconfig-repo

Initialize the local repo:
git init

NOTE:
Debugging problems with Spring Cloud Config Server - V2
https://github.com/in28minutes/spring-microservices-v2/blob/main/03.microservices/01-step-by-step-changes/microservices-v2-1.md#spring-cloud-config-server---steps-01-to-08


Create the file : limits-service.properties in the new local git repo. And add it to the stage (commit)
The path of the such file is like:
/home/juanjo/dev/github/learning/java/microservices/git-localconfig-repo/limits-service.properties


Config the local git folder in the application.properties
spring.cloud.config.server.git.uri=file:///home/juanjo/dev/github/learning/java/microservices/git-localconfig-repo
WINDOWS EXAMPLE: file:///C:/Users/dev/github/learning/java/microservices/git-localconfig-repo

Enable the ConfigServer in the Configuration class
[source,java]
----
@EnableConfigServer
@SpringBootApplication
public class SpringCloudConfigServerApplication {
----

Go to URL:
http://localhost:8888/limits-service/default

IMPORTANT: The name in the URL must match the name of the properties file in the Git repository. The Path declared in the spring.cloud.config.server.git.uri=file:// shouldn't include the name of the file.


== CONNECT LIMITS SERVICE TO SPRING CLOUD CONFIG SERVER

spring-cloud-starter-config
It comes from Sping Initializer dependency: "Config Client" (Spring Cloud Config)
This dependency helps to talk to the config server

It's important to configure the name of the application, What configuration in the cloud-config-server should this application make use of?

IMPORTANT: The name of the application configured in the service must match the name of the properties in the repository

Example:
In the limits-service project we have:
spring.application.name=limits-service

In the repository there is a file qith name:
limits-service.properties

== CONFIGURING MULTIPLE PROFILES FOR LIMITS SERVICE

Create differents files for each environment in the repository:
limits-service-dev.properties
limits-service-qa.properties
limits-service.properties (default)

Go to URL:
http://localhost:8888/limits-service/default
http://localhost:8888/limits-service/dev
http://localhost:8888/limits-service/qa


And to configure which environment the application should use from config-server, you should configure the properties in the application project:
spring.profiles.active=dev

NOTE: If the profile is still 'default' maybe an additional config could be reuqired: spring.cloud.config.profile=dev

== DEBUGGING GUIDE

https://github.com/in28minutes/spring-microservices-v2/blob/main/03.microservices/01-step-by-step-changes/microservices-v2-1.md#spring-cloud-config-server---steps-01-to-08


== OVERVIEW OF MICROSERVICES TO BE DEVELOPED
CURRENCY EXCHANGE MICROSERVICE
What is the exchange rate of one currency in another?


CURRENCY CONVERSION MICROSERVICE
Convert 10 USD into INR


Currency Conversion Microzervice -> Currency Exchange Microservice
									|
									DataBase


== CURRENCY EXCHANGE SERVICE
currency-exchange-service
Dependencies:
DevTools
Actuator
Web
ConfgiClient

Add this line to the properties file, is required in order to startup:
spring.config.import=optional:configserver:http://localhost:8888
And additional parameters:
spring.application.name=currency-exchange
server.port=8000

=== URL AND RESPONSE STRUCTURE

URL
http://localhost:8000/currency-exchange/from/USD/to/INR
Response Structure
[source,json]
----
{
   "id":10001,
   "from":"USD",
   "to":"INR",
   "conversionMultiple":65.00,
   "environment":"8000 instance-id"
}
----


== SETTING UP DYNAMIC PORT IN THE RESPONSE

Load Balancing

									Currency Conversion Microservice
									|
									Load Balancer -> Naming Server
									|
				|					|											|
Currency Exchange - Instance 1  |  Currency Exchange - Instance 2  |  Currency Exchange - Instance 3


Add the field 'environment' to the CurrencyExchange bean
In this new field 'environment' we are going to set the value of the port.

Add the Environment Interface to the controller:
import org.springframework.core.env.Environment;

@RestController
public class CurrencyExchangeController {

	@Autowired
	private Environment environment;

Then:
[source,java]
----
	String port = environment.getProperty("local.server.port");
	currencyExchange.setEnvironment(port);
----


== CONFIGURE JPA AND INITIALIZED DATA

Add the Dependency:

	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-data-jpa</artifactId>
	</dependency>

	<dependency>
		<groupId>com.h2database</groupId>
		<artifactId>h2</artifactId>
	</dependency>

configure in application properties:
spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true


Create the JPA entity:
@Entity
public class CurrencyExchange {

	@Id
	private Long id;

	@Column(name="currency_from")
	private String from;

	@Column(name="currency_to")
	private String to;


Insert data into the new created table, create the file data.sql in the resources:
insert into CURRENCY_EXCHANGE(id, currency_from, currency_to, conversion_multiple, environment)
values(10001, 'USD', 'INR', 65, '');
insert into CURRENCY_EXCHANGE(id, currency_from, currency_to, conversion_multiple, environment)
values(10002, 'EUR', 'INR', 75, '');
insert into CURRENCY_EXCHANGE(id, currency_from, currency_to, conversion_multiple, environment)
values(10003, 'AUD', 'INR', 25, '');


DEFER THE EXECUTION OF DATA, Modify the properties file:
spring.jpa.defer-datasource-initialization=true


=== Create JPA Repository

[source,java]
----
public interface CurrencyExchangeRepository
		extends JpaRepository<CurrencyExchange, Long> {
	CurrencyExchange findByFromAndTo(String from, String to);
}
----


call the method in the controller:
CurrencyExchange currencyExchange = repository.findByFromAndTo(from, to);


== CREATE THE CURRENCY CONVERSION SERVICE
Dependencies:
DevTools
Actuator
Web
ConfgiClient  -> spring.config.import=optional:configserver:http://localhost:8888


First configurations in application.properties:
spring.application.name=currency-conversion
server.port=8100
spring.config.import=optional:configserver:http://localhost:8888


=== URL and Response Structure
URL
http://localhost:8100/currency-conversion/from/USD/to/INR/quantity/10

Response Structure
{
  "id": 10001,
  "from": "USD",
  "to": "INR",
  "conversionMultiple": 65.00,
  "quantity": 10,
  "totalCalculatedAmount": 650.00,
  "environment": "8000 instance-id"
}


[source,java]
----
@RestController
public class CurrencyConversionController {

	@GetMapping("/currency-conversion/from/{from}/to/{to}/quantity/{quantity}")
	public CurrencyConversion calculateCurrencyConversion(@PathVariable String from,
														@PathVariable String to,
														@PathVariable BigDecimal quantity) {
----

== INVOKING CURRENCY EXCHANGE FROM CURRENCY
Use a RestTemplate
import org.springframework.web.client.RestTemplate;

		ResponseEntity<CurrencyConversion> responseEntity = new RestTemplate().getForEntity(
				"http://localhost:8000/currency-exchange/from/{from}/to/{to}",
				CurrencyConversion.class, uriVariables);
		return new CurrencyConversion(responseEntity.getBody(), quantity);


== USING FEIGN REST CLIENT FOR SERVICE INVOCATION
In the conversion service, Add the dependency:
		<!-- Feign -->
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-openfeign</artifactId>
		</dependency>

Now create a proxy:
@FeignClient(name="currency-exchange", url="localhost:8000")
public interface CurrencyExchangeProxy {

	@GetMapping("/currency-exchange/from/{from}/to/{to}")
	public CurrencyConversion retrieveExchangeValue(
			@PathVariable String from,
			@PathVariable String to);


Use the proxy on the controller:
		return new CurrencyConversion(proxy.retrieveExchangeValue(from, to), quantity);


== NAMING SERVER and Setting up EUREKA Naming Server
Load Balancer -> Naming Server
Service Registry or Naming Server: All instances of microservices will be registered in the Service Registry

Create a new Spring boot project:
(naming-server)
Dependencies:
DevTools
Actuator
Eureka Server


Add the annotation configuration:
@EnableEurekaServer
@SpringBootApplication
public class NamingServerApplication {

Configure the app name and port:
spring.application.name=naming-server
server.port=8761

To avoid register the app with itself(the Eureka register):
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

Launch the app and go to the url:
http://localhost:8761/

=== Debugging problems with Eureka:

Top Recommendation From Debugging Guide:

Give these settings a try individually in application.properties of all microservices (currency-exchange, currency-conversion) to see if they help

eureka.instance.prefer-ip-address=true
OR

eureka.instance.hostname=localhost

=== Connecting Currency Conversion & Currency Exchange

In the pom.xml of both services(Conversion and Exchange) add this dependency:

		<!-- Naming Server - Eureka -->
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
		</dependency>

And configure the serviceUrl in both services, Exchange and conversion service:
application.properties:
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

== LOAD BALANCING With Eureka, Feign & Spring Cloud LoadBalancer

Load Balancing

									Currency Conversion Microservice
									|
									Load Balancer -> Naming Server
									|
				|					|											|
Currency Exchange - Instance 1  |  Currency Exchange - Instance 2  |  Currency Exchange - Instance 3

Just configure the proxy previously created, by removing the url parameter and only  provide the name of the service, this name is registered in Erukea server. Eureka automatically will balance the request to the many instances of Exchange service.


@FeignClient(name="currency-exchange")
public interface CurrencyExchangeProxy {

Now start a second instance of Exchange Service, and whe load will be balanced between both instances:

http://localhost:8100/currency-conversion-feign/from/USD/to/INR/quantity/10


  "environment": "8000"
}
and
  "environment": "8001"
}

IMPORTANT: CLIENT SIDE LOAD BALANCING is demostrated with this example, using a Proxy(Feign) in the Exchange service that talk with Eureka(naming Server and load balancing)

The netflix-eureka-client add a load balancer in the dependency



